author: 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: App-Cmd
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long::Descriptive: 0.04
  Module::Pluggable::Object: 0
version: 0.002
