---
abstract: 'write command line apps with less suffering'
author:
  - '-2006, (code (simply)).  App::Cmd and bundled code are free'
build_requires:
  IO::TieCombine: 1
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Cmd
name: App-Cmd
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long::Descriptive: 0.06
  Module::Pluggable::Object: 0
  Sub::Exporter: 0.975
  Sub::Install: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/app-cmd
version: 0.203
